config/routes.rb
FruitsVeggies::Application.routes.draw do

  root 'fruits#index'

  resources :fruits
  

end

app/models/fruit.rb
class Fruit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController

  def index
    @fruits = Fruit.all
  end

  def new
    @fruit = Fruit.new
  end

  def create
    Fruit.create(fruit_params)
    redirect_to root_path
  end

  private 

  def fruit_params
    params.require(:fruit).permit(:name, :fruitorveggie, :benefits)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/views/fruits/index.html.erb
<h1 class="booyah-box col-xs-10 col-xs-offset-1">Learn about the health benefits of fruits and vegetables!</h1>

<% @fruits.each do |fruit| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h2><%= fruit.name %></h2>
    <br />
    <p><%= fruit.fruitorveggie %></p>
    <p><%= fruit.benefits %></p>
  </div>

  <hr />
<% end %>

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <%= link_to new_fruit_path do %>
    <i class="glyphicon glyphicon-plus-sign"></i>
    Add more fruits and vegetables to our list!
  <% end %>
</div>

app/views/fruits/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add more fruits and vegetables!</h1>
  <br />
  <%= simple_form_for @fruit do |f| %>
    <%= f.input :name, placeholder: 'Orange' %> 
    <%= f.input :fruitorveggie, :label => 'Fruit or vegetable?', as: :radio_buttons,
    collection: ['Fruit', 'Vegetable'], wrapper: :vertical_radio_and_checkboxes %>
    <%= f.input :benefits, placeholder: 'High in Vitamin C' %>
    <br />
    <%= f.submit 'Add', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FruitsVeggies</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>